# Generated by Django 2.2 on 2020-01-27 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=450, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_name', models.CharField(blank=True, max_length=450, null=True)),
                ('frequency', models.IntegerField(null=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urlSeracher.URL')),
            ],
        ),
    ]
